name: 🎽 CI

on:
  push:
    branches:
      - main
    paths:
      - "**.ts"
      - deno.lock
      - .github/actions/setup-deno-with-cache
      - .github/workflows/ci.yml
  pull_request:
    paths:
      - "**.ts"
      - deno.lock
      - .github/actions/setup-deno-with-cache
      - .github/workflows/ci.yml

jobs:
  lint:
    name: 🧹 Lint
    runs-on: Ubuntu-Latest

    steps:
      - name: 🚚 Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: 🦕 Setup Deno with Cache
        uses: 5ouma/utils/setup-deno-with-cache@b7d4ee85b930f3385155f60be3a05aef8d3e5ad6 # main

      - name: 🧹 Lint Check
        run: deno lint

      - name: 📚 Lint the JSDoc
        run: deno doc --lint ./src

  format:
    name: 📝 Format
    runs-on: Ubuntu-Latest

    steps:
      - name: 🚚 Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: 🦕 Setup Deno with Cache
        uses: 5ouma/utils/setup-deno-with-cache@b7d4ee85b930f3385155f60be3a05aef8d3e5ad6 # main

      - name: 📝 Format Check
        run: deno fmt --check

  type-check:
    name: 🔍 Type Check
    runs-on: Ubuntu-Latest

    steps:
      - name: 🚚 Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: 🦕 Setup Deno with Cache
        uses: 5ouma/utils/setup-deno-with-cache@b7d4ee85b930f3385155f60be3a05aef8d3e5ad6 # main

      - name: 🔍 Type Check
        run: deno check --doc ./src

  test:
    name: 🧪 Test
    runs-on: Ubuntu-Latest

    steps:
      - name: 🚚 Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: 🦕 Setup Deno with Cache
        uses: 5ouma/utils/setup-deno-with-cache@b7d4ee85b930f3385155f60be3a05aef8d3e5ad6 # main

      - name: 🧪 Run Tests
        run: deno task cov

      - name: ☂️ Upload Coverage
        uses: codecov/codecov-action@1e68e06f1dbfde0e4cefc87efeba9e4643565303 # v5.1.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
